
[Config]
	#Raids Configurations
	#Controlls whether the Shogun spawns in raids, usually set to true
	"Shogun Raid Spawning" = true
	#Controlls whether the Samurai spawns in raids, usually set to true
	"Samurai Raid Spawning" = true
	#Controlls whether the Guard spawns in raids, usually set to true
	"Guard Raid Spawning" = true
	#Controlls whether the Blastioner spawns in raids, usually set to true
	"Blastioner Raid Spawning" = true
	#Controlls whether the Royal Longaxe Guards spawns in raids, usually set to false
	"Royal Longaxe Guards Raid Spawning" = false
	#Controlls whether the Cowboy spawns in raids, usually set to true
	"Cowboy Raid Spawning" = true

	[Config."Raid Wave Member Configuration"]
		#    Samurai Wave Counts
		#    Requires a list of no more and no less than 8 integers, each corresponding to its respective wave.
		#
		"Shogun Wave Counts" = [0, 0, 0, 0, 0, 0, 1, 1]
		#    Samurai Wave Counts
		#    Requires a list of no more and no less than 8 integers, each corresponding to its respective wave.
		#
		"Samurai Wave Counts" = [0, 0, 1, 1, 0, 1, 1, 2]
		#    Guard Wave Counts
		#    Requires a list of no more and no less than 8 integers, each corresponding to its respective wave.
		#
		"Guard Wave Counts" = [0, 0, 0, 1, 1, 0, 1, 1]
		#    Blastioner Wave Counts
		#    Requires a list of no more and no less than 8 integers, each corresponding to its respective wave.
		#
		"Blastioner Wave Counts" = [0, 0, 0, 0, 0, 1, 0, 1]
		#    Knights Wave Counts
		#    Requires a list of no more and no less than 8 integers, each corresponding to its respective wave.
		#
		"Knights Wave Counts" = [0, 0, 0, 0, 1, 0, 1, 1]
		#    Cowboy Wave Counts
		#    Requires a list of no more and no less than 8 integers, each corresponding to its respective wave.
		#
		"Cowboy Wave Counts" = [0, 1, 0, 1, 0, 1, 0, 1]

